export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const CLEAR_LOADING_AND_ERROR = 'CLEAR_LOADING_AND_ERROR';
export const SET_CURRENCY_USD_TO_UAH = 'SET_CURRENCY_USD_TO_UAH';


