export const START_REGISTER = 'SET_REGISTER';
export const SUCCESS_REGISTER = 'SUCCESS_REGISTER';
export const SET_ERROR_AUTH = 'SET_ERROR_AUTH';

export const SET_USER_EMAIL = 'SET_USER_EMAIL';
export const SET_USER_PASSWORD = 'SET_USER_PASSWORD';
