
export const SUCCESS_REGISTER = 'SUCCESS_REGISTER';
export const SUCCESS_AUTH = 'SUCCESS_AUTH';

export const SET_USER_EMAIL = 'SET_USER_EMAIL';
export const SET_USER_PASSWORD = 'SET_USER_PASSWORD';
