export const SET_COMMON_MONEY = 'SET_COMMON_MONEY';
export const CHANGE_COMMON_MONEY_VALUE = 'CHANGE_COMMON_MONEY_VALUE';
export const CHANGE_COMMON_MONEY_CURRENCY = 'CHANGE_COMMON_MONEY_CURRENCY';


