export const START_LOAD_SHOPPING_LIST = "START_LOAD_SHOPPING_LIST";
export const SET_SHOPPING_LIST_ERROR = 'SET_SHOPPING_LIST_ERROR';
export const SUCCESS_GET_SHOPPING_LIST = 'SUCCESS_GET_SHOPPING_LIST';
export const DELETE_SHOPPING_LIST_ELEMENT = 'DELETE_SHOPPING_LIST_ELEMENT';
export const SET_LIKE_STATUS = 'SET_LIKE_STATUS';
export const SET_DONE_STATUS = 'SET_DONE_STATUS';
export const ADD_NEW_SHOPPING_LIST_ITEM = 'ADD_NEW_SHOPPING_LIST_ITEM';
export const CHANGE_NEW_LIST_ITEM_VALUE = 'CHANGE_NEW_LIST_ITEM_VALUE';
